# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20171121_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.Book'),
            preserve_default=False,
        ),
    ]
