# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'dogs',
            },
        ),
    ]
