# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
