# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
